
MODEL_INFO = {
    "tiny": {"vram": "1 GB", "speed": "10x"},
    "base": {"vram": "1 GB", "speed": "7x"},
    "small": {"vram": "2 GB", "speed": "4x"},
    "medium": {"vram": "5 GB", "speed": "2x"},
    "large": {"vram": "10 GB", "speed": "1x"},
    "turbo": {"vram": "6 GB", "speed": "8x"}
}

# Update LANGUAGETRANS dictionary to ensure consistent naming and coding
LANGUAGETRANS = {
    'Auto': 'auto',
    'English': 'en',
    'Thai': 'th',
    'Spanish': 'es',
    'French': 'fr',
    'German': 'de',
    'Italian': 'it',  # Changed from 'it-IT' to match standard code
    'chinese (simplified)': 'zh-CN', 
    'chinese (traditional)': 'zh-TW',
    'Japanese': 'ja',
    'Korean': 'ko',
    'Vietnamese': 'vi',
    'Russian': 'ru',
    # Additional languages for consistency with LANGUAGE_CODES_AI
    'Portuguese': 'pt',
    'Turkish': 'tr',
    'Polish': 'pl',
    'Dutch': 'nl',
    'Arabic': 'ar',
    'Swedish': 'sv',
    'Indonesian': 'id',
    'Hindi': 'hi',
    'Finnish': 'fi',
    'Hebrew': 'iw',  # Note: Google uses 'iw' for Hebrew
    'Ukrainian': 'uk',
    'Greek': 'el',
}


LANGUAGE_CODES_AI = [
    ("auto", "Auto"),
    ("en", "English"),
    ("zh", "chinese"),
    ("ja", "Japanese"),
    ("ko", "Korean"),
    ("de", "German"),
    ("es", "Spanish"),
    ("ru", "Russian"),
    ("fr", "French"),
    ("pt", "Portuguese"),
    ("tr", "Turkish"),
    ("pl", "Polish"),
    ("ca", "Catalan"),
    ("nl", "Dutch"),
    ("ar", "Arabic"),
    ("sv", "Swedish"),
    ("it", "Italian"),
    ("id", "Indonesian"),
    ("hi", "Hindi"),
    ("fi", "Finnish"),
    ("vi", "Vietnamese"),
    ("iw", "Hebrew"),
    ("uk", "Ukrainian"),
    ("el", "Greek"),
    ("ms", "Malay"),
    ("cs", "Czech"),
    ("ro", "Romanian"),
    ("da", "Danish"),
    ("hu", "Hungarian"),
    ("ta", "Tamil"),
    ("no", "Norwegian"),
    ("th", "Thai"),
    ("ur", "Urdu"),
    ("hr", "Croatian"),
    ("bg", "Bulgarian"),
    ("lt", "Lithuanian"),
    ("la", "Latin"),
    ("mi", "Maori"),
    ("ml", "Malayalam"),
    ("cy", "Welsh"),
    ("sk", "Slovak"),
    ("te", "Telugu"),
    ("fa", "Persian"),
    ("lv", "Latvian"),
    ("bn", "Bengali"),
    ("sr", "Serbian"),
    ("az", "Azerbaijani"),
    ("sl", "Slovenian"),
    ("kn", "Kannada"),
    ("et", "Estonian"),
    ("mk", "Macedonian"),
    ("br", "Breton"),
    ("eu", "Basque"),
    ("is", "Icelandic"),
    ("hy", "Armenian"),
    ("ne", "Nepali"),
    ("mn", "Mongolian"),
    ("bs", "Bosnian"),
    ("kk", "Kazakh"),
    ("sq", "Albanian"),
    ("sw", "Swahili"),
    ("gl", "Galician"),
    ("mr", "Marathi"),
    ("pa", "Punjabi"),
    ("si", "Sinhala"),
    ("km", "Khmer"),
    ("sn", "Shona"),
    ("yo", "Yoruba"),
    ("so", "Somali"),
    ("af", "Afrikaans"),
    ("oc", "Occitan"),
    ("ka", "Georgian"),
    ("be", "Belarusian"),
    ("tg", "Tajik"),
    ("sd", "Sindhi"),
    ("gu", "Gujarati"),
    ("am", "Amharic"),
    ("yi", "Yiddish"),
    ("lo", "Lao"),
    ("uz", "Uzbek"),
    ("fo", "Faroese"),
    ("ht", "Haitian Creole"),
    ("ps", "Pashto"),
    ("tk", "Turkmen"),
    ("nn", "Nynorsk"),
    ("mt", "Maltese"),
    ("sa", "Sanskrit"),
    ("lb", "Luxembourgish"),
    ("my", "Myanmar"),
    ("bo", "Tibetan"),
    ("tl", "Tagalog"),
    ("mg", "Malagasy"),
    ("as", "Assamese"),
    ("tt", "Tatar"),
    ("haw", "Hawaiian"),
    ("ln", "Lingala"),
    ("ha", "Hausa"),
    ("ba", "Bashkir"),
    ("jw", "Javanese"),
    ("su", "Sundanese"),
]

MODEL_TYPES = ["tiny", "base", "small", "medium", "large"]

TASK_TYPES = ["transcribe", "translate"]